#!/usr/bin/env bash

## PROYECTO_COMPLETIONS_INSTALLED
_proyecto-completions()
{
    local cur=${COMP_WORDS[COMP_CWORD]}
    COMPREPLY=( $(compgen -W "`ad completions`" -- $cur) )
}
complete -F _proyecto-completions ad
